services:
  mysql:
    image: mysql:8.0
    container_name: digicakra_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digicakra
      MYSQL_USER: digicakra_user
      MYSQL_PASSWORD: digicakra_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
